### ISSUE TITLE
Gcc errors when compiling Zeo++

### ISSUE THREAD

**Issue by feacluster** [learningmatter-mit/VOID#2]
I am following the instructions here for the pymatgen.io.zeopp module:

https://pymatgen.org/pymatgen.io.zeopp.html#zeo-installation-steps

I get gcc errors when attempting step 5(c). The first error is:

zeo/netstorage.cpp: In function ‘PyObject* __Pyx_PyCFunction_FastCall(PyObject*,
zeo/netstorage.cpp:8776:69: error: too many arguments to function
return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);

This is then followed by a few other errors before the compilation fails.

I have tried with GCC 8.3.1 and 4.8.5 but get the same errors.

Perhaps this only works with a specific GCC version? Or could it be something else?

**Comment by dskoda** [comment]
@feacluster I was able to reproduce the steps described in the pymatgen documentation using the following requirements:

 - gcc 7.5.0
 - python 3.6.8 on a conda 4.7.12 environment
 - cython 0.29.5

Please note that there may be differences between the Zeo++ code in the subversion repository and the stable version available for download in [this link](http://www.maciejharanczyk.info/Zeopp/ ). I was able to compile the code normally by downloading Zeo++ with `svn checkout https://code.lbl.gov/svn/zeo/trunk --username anonsvn`. If you have any other problems compiling this library, please try contacting the Zeo++ developers.

**Comment by feacluster** [comment]
I tried again on a fresh system with Python 3.7.10, gcc 7.2 and cython 0.29 . Got stuck on the same errors. I feel I must be doing something wrong in the installatio steps. Perhaps I am not doing them in the right order? Here are the commands I am running:

```
module load intel/python3.7/2020.2
conda upgrade conda
conda create -n VOID python=3.7 numpy networkx pymatgen=2020.3.2 scikit-learn -c conda-forge
conda activate VOID
cd VOID-master
pip install .
pip install --user cython
cd voro/trunk
nano config.mk ( add -fPIC option to CFLAGS )
make clean
make
cd zeo/trunk
make clean
make dylib
cd cython_wrapper/
nano setup_alt.py (  change includedirs=["/myhome/voro/trunk/src", ".."]
python setup_alt.py develop --user
```

Then the errors appear

**Comment by dskoda** [comment]
Please note that the Zeo++ code expects the following tree structure:

```
.
├── Voro++
│   └── voro
│       └── trunk
└── Zeo++
    └── zeo
        └── trunk
```

You can either move the folders to have that tree structure, or change  `Zeo++/zeo/trunk/Makefile` to include the correct paths in `VOROINCLDIR` and `VOROLINKDIR`. I was able to compile the Zeo++ normally with the tree structure above.

**Comment by feacluster** [comment]
That's right, I did edit the Makefile to change VOROINCLDIR and VOROLINKDIR. 

I only get the errors when running, "python setup_alt.py develop --user" . Everything else compiles without any issue. So perhaps some python issue?

**Comment by dskoda** [comment]
I was unable to reproduce these errors following your instructions step-by-step. Are you sure you're using the right `python` executable, i.e. the one inside the conda environment?

**Comment by feacluster** [comment]
Made some progress by using Python 3.6.8 instead of 3.7 . The compiler errors went away and it seemed to complete ok.

Next I went to test via your command:

`python dock.py ../VOID/tests/files/{AFI.cif,molecule.xyz} -o ~/Desktop/docked -d batch -s voronoi_cluster -f min_distance`

However, I get this error:

   from VOID.io.stdout import suppress_stdout
ModuleNotFoundError: No module named 'VOID.io'

Perhaps related to the pymatgen version? I am using 2021.2.8 .

**Comment by feacluster** [comment]
An update: Seems I get no error when I run the dock.py test from this folder:

/myhome/VOID-master

If I run it from any other folder then I get the error. The strange thing is I can "import VOID"s ok from any directory. But importing VOID.io gives error. I suspect this has to do with the "pip install ."  command. I also tried "pip install . --user" but it did not change the error.

(VOID) [admhussaif1@hpclogin01 ~]$ python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import VOID
>>> from VOID.io.stdout import suppress_stdout
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'VOID.io'
>>>

**Comment by dskoda** [comment]
Thanks. I fixed this error in the last commit. Please `git pull` from the repo and try running `pip uninstall VOID` and `pip install .` again. Then, you should be able to run `dock.py` as a normal executable as long as you're in the conda environment.

**Comment by feacluster** [comment]
Great, seems to be working now!
