### ISSUE TITLE
pymatgen installation help

### ISSUE THREAD

**Issue by cwaitt** [learningmatter-mit/VOID#5]
Hello. I am trying to install VOID and the Zeo++ dependencies. All seems to be working installing VOID, but when I use the svn checkout command to get Voro++ and Zeo++, I get an "access forbidden" error and was hoping you can provide some guidance on how to resolve this issue.

**Comment by dskoda** [comment]
Thanks for reporting this problem. I confirm I can reproduce it.

It seems the LBL restricted the access to the SVN code for Voro++ and Zeo++, previously available at https://code.lbl.gov/svn/voro/trunk, and https://code.lbl.gov/svn/voro/trunk.

I noticed, however, that there are a few mirrors available on Github. The [Github Voro++ repo](https://github.com/chr1shr/voro) is maintained by the original developer of Voro++, and is likely to be compatible with the installation tutorial on pymatgen (and reproduced in the docs of this repo). Zeo++ has a [mirror](https://github.com/richardjgowers/zeoplusplus) last uploaded on 2018.

Please let me know if you can proceed the installation of these packages using the mirrors. If so, I'll update the documentation for installing VOID. Otherwise, we'll have to find a workaround or chat with the Zeo++/Voro++ developers. Thanks.

**Comment by cwaitt** [comment]
So this solution seems to work (partly). I was able to clone these mirrors into my VOID directory, and compile the files as specified on the pymatgen website (https://pymatgen.org/installation.html). I needed to edit the config and Makefiles to point in the right directions. However, once I get to the last section, where it asks to type "python setup_alt.py develop" I get an error with gcc, and having no experience with C, I have no idea how to interpret the error message. Any suggestions?

---
running develop
running egg_info
writing zeo.egg-info/PKG-INFO
writing dependency_links to zeo.egg-info/dependency_links.txt
writing top-level names to zeo.egg-info/top_level.txt
reading manifest file 'zeo.egg-info/SOURCES.txt'
writing manifest file 'zeo.egg-info/SOURCES.txt'
running build_ext
skipping 'zeo/voronoicell.cpp' Cython extension (up-to-date)
skipping 'zeo/netstorage.cpp' Cython extension (up-to-date)
building 'zeo.netstorage' extension
/opt/crc/g/gcc/8.3.0/bin/gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I../../../../Voro++/voro/trunk/src -I.. -I/opt/crc/p/python/3.7.3/gcc/include/python3.7m -c zeo/netstorage.cpp -o build/temp.linux-x86_64-3.7/zeo/netstorage.o
In file included from zeo/../../network.h:40,
                 from zeo/netstorage.cpp:426:
zeo/../../material.h: In constructor ‘MATERIAL::MATERIAL()’:
zeo/../../material.h:138:29: warning: unused variable ‘rad_con’ [-Wunused-variable]
    container_periodic_poly *rad_con = NULL;
                             ^~~~~~~
zeo/../../material.h:139:26: warning: unused variable ‘no_rad_con’ [-Wunused-variable]
    container_periodic   *no_rad_con = NULL;
                          ^~~~~~~~~~
zeo/netstorage.cpp: In function ‘PyObject* __Pyx_PyCFunction_FastCall(PyObject*, PyObject**, Py_ssize_t)’:
zeo/netstorage.cpp:8776:69: error: too many arguments to function
     return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);
                                                                     ^
zeo/netstorage.cpp:8766:15: warning: unused variable ‘result’ [-Wunused-variable]
     PyObject *result;
               ^~~~~~
zeo/netstorage.cpp:8767:9: warning: unused variable ‘flags’ [-Wunused-variable]
     int flags;
         ^~~~~
zeo/netstorage.cpp: In function ‘void __Pyx__ExceptionSwap(PyThreadState*, PyObject**, PyObject**, PyObject**)’:
zeo/netstorage.cpp:10133:24: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?
     tmp_type = tstate->exc_type;
                        ^~~~~~~~
                        curexc_type
zeo/netstorage.cpp:10134:25: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?
     tmp_value = tstate->exc_value;
                         ^~~~~~~~~
                         curexc_value
zeo/netstorage.cpp:10135:22: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
     tmp_tb = tstate->exc_traceback;
                      ^~~~~~~~~~~~~
                      curexc_traceback
zeo/netstorage.cpp:10136:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?
     tstate->exc_type = *type;
             ^~~~~~~~
             curexc_type
zeo/netstorage.cpp:10137:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?
     tstate->exc_value = *value;
             ^~~~~~~~~
             curexc_value
zeo/netstorage.cpp:10138:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
     tstate->exc_traceback = *tb;
             ^~~~~~~~~~~~~
             curexc_traceback
zeo/netstorage.cpp: In function ‘PyObject* __Pyx_PyObject_CallMethod1(PyObject*, PyObject*, PyObject*)’:
zeo/netstorage.cpp:193:48: warning: suggest parentheses around comparison in operand of ‘&’ [-Wparentheses]
     ((PyCFunction_Check(func) && METH_FASTCALL == PyCFunction_GET_FLAGS(func) & ~(METH_CLASS | METH_STATIC | METH_COEXIST)))
zeo/netstorage.cpp:10173:17: note: in expansion of macro ‘__Pyx_PyFastCFunction_Check’
             if (__Pyx_PyFastCFunction_Check(function)) {
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from zeo/../../networkstorage.h:13,
                 from zeo/../../voronoicell.h:29,
                 from zeo/netstorage.cpp:423:
zeo/../../mindist.h: At global scope:
zeo/../../mindist.h:13:33: warning: ‘bz’ defined but not used [-Wunused-variable]
 static double bx,bxy,by,bxz,byz,bz;
                                 ^~
zeo/../../mindist.h:13:29: warning: ‘byz’ defined but not used [-Wunused-variable]
 static double bx,bxy,by,bxz,byz,bz;
                             ^~~
zeo/../../mindist.h:13:25: warning: ‘bxz’ defined but not used [-Wunused-variable]
 static double bx,bxy,by,bxz,byz,bz;
                         ^~~
zeo/../../mindist.h:13:22: warning: ‘by’ defined but not used [-Wunused-variable]
 static double bx,bxy,by,bxz,byz,bz;
                      ^~
zeo/../../mindist.h:13:18: warning: ‘bxy’ defined but not used [-Wunused-variable]
 static double bx,bxy,by,bxz,byz,bz;
                  ^~~
zeo/../../mindist.h:13:15: warning: ‘bx’ defined but not used [-Wunused-variable]
 static double bx,bxy,by,bxz,byz,bz;
               ^~
error: command '/opt/crc/g/gcc/8.3.0/bin/gcc' failed with exit status 1

**Comment by dskoda** [comment]
My colleague @mingrouxie was able to reproduce the installation steps of VOID using the Zeo++ and Voro++ mirrors. An updated README with the instructions, including tips on how to proceed with the compilation of the dependencies, was now uploaded to the repository.
